# Generated by Django 3.2.6 on 2022-08-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
